[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "1ba81e44ce9cfa1edd143d80660436dec84515b9"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "2facf8b29f4c3dc8e64d7c36a84886c9188c71db22a69a08fdff0edfa2d21f3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba7028a5f6c6e7311983c1d8b91a0ba7d3879111"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "e6c5c466b1c8e799a11b38e1777cd1c4a41f92530c68ef803821ecc638efea3a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6e3cf6ec56f439b06b74adc06ae3617b247cf3f"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "3739449efa224073b3e84d5b8c2155c0afa47535d779d25b17d6b95215095605"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "4e28c9a58c15e7adf10561c9565dc566ac5ecc2b"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "b54485e104e6142c1291562d658eaf079f461d1f242d5a9696fb7678139c2030"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a45ed2806e15059a40f164be8ccd257becc6e7cb"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "3e2ee91236a68191c07ac9f2614d367dc974fb460c9ab8e6b45805084a6513ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40ea7a939c014c9955ac82e3f55abc15500a74c8"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "60c2a822615e2fa456390c2304ea0027527eab9c2499b264089ae9269c4a1fe5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67cd2faf3629b00f73e49003258f75f7781dd757"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "985763d645f0ad6810ce0d650ced0de2bd22e6adbba7a44d752ca807b9890a14"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "835da418aae985f720ce722bd85f879ac4cded54"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "8af3ade22e2ca71e877deda67c7b3ae384c30f96e39aea2a1204ddc3a80abda5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e8353e9a66cfa8efa77ceb21303c247832e7832"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "217062ae12d51ae934ab1e2810d4028fc526f1ec4132246971afd93c06ba7f15"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd3c0b3027a4b1b198622c5b67b6b4526a90e86e"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "c9c634a198944ebcc1388dcb5b8a4485ab7e7179ca68118c8629f010ea10ee7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebdafce5d1a4dc3be68474ddf2c3c6b81a182513"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "a04120b364fd80fb72263fc48922951fff83aff693b423bf87ab76ee8c46b1b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "802243e128b0a980f0bafaf7b33bdee0cf74b5df"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "a74d780153f4c0f0dcbfc7bd35310465ac46dd65dd6f1ab29d7790f84e891ca1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "f3186269f385bc2a33e124d50c6e99dd067dc0d3"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "c0830bbd8e619a595d05446f48c6f6bf54e0a9c41c379c6df0f8384b0689cdfe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47f8f2d9a7a275a593f7fdc50caff2ae990391b1"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "3e86b5bdc70d9410f401001a56c942cae5b96ccdb39878edecfc66e05f47e9bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a5cb03fb09bd93f60b24a49629c3648e489a2d6"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "594b1d66a00ffe69eee056eab34da2f0b47dcd793f9eca5d0d1f9a9b184e4675"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "c4137370b880098fa1df2e4eeea24baf923cc99d"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "9f939f3de8ed0cb2439654e95785d1833cd80dd0e38e753f74a8c63ea3e475ee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d23fbb13535add49322dded93eebc2863cf31dc5"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "9304428bcfaca449b02edc830aebc8d402fe30d752c688429e21bbb331e8031c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+14/LLVM_full_assert.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
