[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "b0f01b3c2913270277bd08fe816c94cf1b86b622"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "192668aaec31bfaf45fc1c27793193384c91cb708ff64771dee6260cf72db4ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.aarch64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d4678a9406412132ecbbcd7eae5c6952385ae51"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "b4682a0968d0da7e6f9752bcb7e7a4e4f6cb8d6dde9fab7e8add5d99376962ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03c002fe868f611d0eef8dace42d08676a24d9c0"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "e743a401b3f68deeb4362879c95e590228ac520743c09dea3c663a2324fcbe8a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "257d449b033bac934e079e453e68b1521b6c1b8d"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "d02028af3d95c9421ed6ea9378939a4bea2e3704cae86ff5bec43e69d39a7301"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed21b1524721f0c4102dba50076c0d8a5e2341ab"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "379bd830bcb89017c223742b33fbbe8fd3ca4fd1b3afa2fde0cefdeb3aa4d4e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5efd6e82680a89315ce1cc31bd88d8c47bd3f44"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "b136fd92044e471dca54590c2b61e8d3cc2d9db5a63fbae4d182a27b0f0a3f57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00375f0e8cd6b3f5f21dff56fb401ec4c101780f"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "3ba41ee4322310d4582a00f4e15af1a95c0543f4e7bc3e50c28680d2a0dc22aa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "879ed49bdf7277a0a1f662d5dbfd07ef82cd240d"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "058c6021ef625ae0285447666d470f52ad2a5f0250784e0ee039d441493ccf78"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a8f713fb9a04582482efa6f772fda7ad7ec5ca9"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "64d334b318ed26724e95150e97a10796c84169a06a4ea4804727c51eff4716d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8e76efb250e540dbd93654a27cba05c0de68cab"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "dd32bb5139b304704e86e57d518f865b1ed6b1cc24650f16c8628390dec99f55"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b77f5ee851e311b8dbff28a58852eb38dc45cc11"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "a64096f953ba72264f6b7f5236f9d235ff4506af3ca83cbfed6b349e9153b9c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee70b723089a3ed30b84ca876e35abfbf363156e"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "7bd7c09f305897a725a3f88fc76108cda1b1f5ac32d1811f1159da5750fa49c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "25612cc5925b7549e28f9fed53c30febd0c14194"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "41dff0441403f2582ea064ba4e816ceb72ed65d8b77cb7445cb849edf5c8e234"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.x86_64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f3cce8117d29a4e3cac3276f746446dd193fb01"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "9e8db60f3f541fce7e7292dce2837e01b11b2399c681232966b4e5e3edefe5be"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "812c01b8b222da1b2e2d1d30363de2be760aec48"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "13fdef498956f7a61c207c7ef63a5e02ebafddf6bfddf2aa0a77e455c3a4fc33"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "072fc33639a44518ac5e85acb7742d7be1dd3c0a"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "a6e3a575e8fb3591d4637497c06c3e49c1f71c7760520a07be1e4b55f527b26a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af29dd93d7d561f1bf3b084328069613490430b5"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "49d8dde6e78b370a06cf4c412564aac21745475d95e6939320374e77d996c354"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v23.1.1+3/LLVM_full_assert.v23.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
