[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "0cc7062dbfcc0ffd9ec44d6787b33c3fbd457b61"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "58c85292beeb23f22033456bc1f67a6f9d245721030ae1e9875850be4a12b3de"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.aarch64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56b3329c6d0cc5aff1ddab6657707aeb3ec42e1e"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "02e85392ed1fe97366ae5b9f043089362bacc549f3f566e01d1eed0a4b369e2b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0b04586dc8ea11940851f378e1c4430056b7942"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "f75a2f0acfb6a6a934e34135a648de923914fba4136d008314dd646d305e4409"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "0884ff57cbbd85e39eb3f54c393b74e1d624df99"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "f7a3806b34ad3d26678a04354463321ea6f91f95bbd084033ced05f17e56d170"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7da200acd55e2cd75297812ed7e6849e4ded14dc"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "85fc3fa0d888a0015ec67534f6fda7b0fdf1ed5dfa48ab7b2b8d2024712032f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff5ea114710e519c0c5d4cc0ddb1cbe656097dd8"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "3b853f16339175809536a8fa46f9d6ae6cceda6a5aa2782078bccceeb000455f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76480a09d6d01f5ea9f7804403f0a31d8ae589cb"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "8b79695335bd0276fd3d258c7e624c4482744ad9f00e02eb44b6e6174d0a315c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa2f94c21a1a61021fb3e7d5a773586b58691465"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "44e09e3e4812d26df29ad466742f90af2b91902e138f9488ce11d5d58803e031"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd839f830f7d4c902340783a8c0d0a211534d82f"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "c05f382b3dfc5713b2ce13db302b6fd80f96592374aee7392b11eec3a26bcabe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d316cc9d0624835897e80aec55557b5fa0416552"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "898aacceef90392b9ba22866779c7e42e9008c15cbcef9c3fb2b6661f9814e90"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cebdae4baa2a7ad4a5d1b7eb4c135b63b816daff"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "a6a3535543a8f088b0c6ab411eee3070b3867f7f7f10377fc0b968419a5a3da3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46cd7d56837a5141e056dc2525e717250c98cd3a"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "a759a4e8753d31c18a66e40a9188c68e894e88fd2962a3d95e22f258d143fe52"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "7c00e2bbf3890be3c873f38667fccc00d057e419"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "cd1d9323161f72081a567272e2750dbdc1eeb9f1a385ec0ca174dc40da007e31"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.x86_64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0688682cbea068fa8a4e6b6400c76cb470e0d6a1"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "449d2f8d0747374938bec095b71e062f58a65003f8cd973707088d3d72cc99a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c33e3c8414c0a4678e2f5baf8487f09c959fed2"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "1a61f6b1ffb2de8ba07928d952e413a581c2185676d8339726dc355a24376c99"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "dfab467c904c99da6f42b5adb09f7698d0c9840d"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "dad28911ee2bcd0dbeb1b2853c67e6b376e5ffb110c0758485c03e1b47494162"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2197206d8ce37507b8dc6ec3e6f639cdff36571"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "235c46b6d75e99e6720e3ba20cd907c9ec06e2a38fef5fd37bcd1b8c025ce9d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v21.1.8+1/LLVM_full_assert.v21.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
